name: Javadoc

on:
  push:
    tags:
      - 'v*'

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 11
      - run: ./gradlew javadoc
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/javadoc
      - id: deployment
        uses: actions/deploy-pages@v4
